services:
  # Backend Server
  backend-server:
    env_file:
      - ./backend/server/.env
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    command: npm run start-watch
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - ./backend/server/src:/code/src:rw
      - ./backend/server/package.json:/code/package.json
      - ./backend/server/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - frontend-backend
      - backend-db
    depends_on:
      db:
        condition: service_healthy

  # Database (MySQL)
  db:
    env_file:
      - ./backend/db/.env
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend-db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # Frontend Client
  frontend-client:
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/client/src:/code/src
      - /code/node_modules
    networks:
      - frontend-backend
    depends_on:
      backend-server:
        condition: service_healthy

# Networks configuration
networks:
  frontend-backend:
    driver: bridge
  backend-db:
    driver: bridge

# Volumes
volumes:
  back-notused:
  db-data:
