services:
  # Backend users micro
  backend-users:
    container_name: users
    env_file:
      - ./backend/users/.env
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    command: npm run start-watch
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - ./backend/users/src:/code/src:rw
      - ./backend/users/package.json:/code/package.json
      - ./backend/users/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - client-server
      - server-db
    depends_on:
      db:
        condition: service_healthy

  # Database (MySQL) micro
  db:
    container_name: db
    env_file:
      - ./backend/db/.env
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - server-db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # Frontend expo micro
  frontend-expo:
    container_name: expo
    env_file:
      - ./frontend/myapp/.env
    build:
      context: ./frontend/myapp
      dockerfile: Dockerfile
    networks:
      - client-server
    #network_mode: "host"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend/myapp/:/opt/my-app/
      - /code/node_modules
    #depends_on:
    #  backend-server:
    #    condition: service_healthy

# Networks configuration
networks:
  client-server:
    driver: bridge
  server-db:
    driver: bridge

# Volumes
volumes:
  back-notused:
  db-data:
