apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories-microservice
  labels:
    app: stories-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stories-microservice
  template:
    metadata:
      labels:
        app: stories-microservice
    spec:
      containers:
      - name: stories-microservice
        image: my-app-backend-stories:latest  # Assicurati che l'immagine contenga wait-for-it.sh
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
