apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: my-app-backend-migration:latest
        restartPolicy: Never  # Non riavviare in caso di errore
        command: ["node", "../backend/migrationsrc/migrate.js"]
        env:
          - name: DB_HOST
            value: "db-service"  # Nome del service Kubernetes che punta al database
          - name: DB_PORT
            value: "3306"  # Cambia porta e altri dettagli se necessario
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        volumeMounts:
        - mountPath: /app
          name: app-files
      restartPolicy: Never
      volumes:
      - name: app-files
        emptyDir: {}
  backoffLimit: 1
