apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==                  # 'mysql-service' in base64 (without newline)
  MYSQL_PORT: MzMwNg==                              # '3306' in base64
  MYSQL_USER: bXlzcWxfdXNlcg==                      # 'mysql_user' in base64
  MYSQL_PASSWORD: dXNlcnBhc3N3b3Jk                  # 'userpassword' in base64
  MYSQL_DATABASE: bXlhcHBfZGI=                      # 'myapp_db' in base64
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkCg==         # 'rootpassword' in base64
  PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUExQlFZREsyVndCQ0lFSUhkejRKT21sOXErOHJySVJqVEVKakFiYnhlZnlzODQ5RmZMK3pkZDhIOWcKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
  PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQTloR3NzbVVvQmRzcWF0eGhQYWVUU2FvazhNUGd4bnJFWUVuS2dvelJZckE9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=