apiVersion: apps/v1
kind: Deployment
metadata:
  name: expo-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: expo-container
        image: 976193259173.dkr.ecr.eu-central-1.amazonaws.com/my-app_frontend-expo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        envFrom:
        - configMapRef:
            name: expo-service-urls