apiVersion: apps/v1
kind: Deployment
metadata:
  name: expo-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: expo-container
        image: my-app-frontend-expo:latest 
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: BACKEND_USERS_URL
          value: users-backend-service.backend-ns.svc.cluster.local:3000