apiVersion: v1
kind: ConfigMap
metadata:
  name: expo-service-urls
data:
  # Expo Public Environment Variables
  EXPO_PUBLIC_URL_USERS: "http://localhost:8000/users/"
  EXPO_PUBLIC_URL_STORIES: "http://localhost:8000/stories/"
  EXPO_PUBLIC_URL_TTS: "http://localhost:8000/speak"
