apiVersion: apps/v1
kind: Deployment
metadata:
  name: expo-frontend-deployment
  namespace: frontend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: expo-container
        image: my-app_frontend-expo:latest # Sostituisci con il nome completo dell'immagine se necessario
        imagePullPolicy: Never
        ports:
        - containerPort: 8081