apiVersion: apps/v1
kind: Deployment
metadata:
  name: expo-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: expo-container
        image: my-app_frontend-expo:latest 
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: EXPO_PUBLIC_URL_STORIES
          value: "http://localhost:8000/stories/"
        - name: EXPO_PUBLIC_URL_USERS
          value: "http://localhost:8000/users/"
        - name: EXPO_PUBLIC_URL_TTS
          value: "http://localhost:8000/tts/"
        - name: EXPO_PUBLIC_URL_AI
          value: "http://localhost:8000/ai/"