apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  rules:
  - http:
      paths:
      # Frontend Route
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy-service
            port:
              number: 8000
