apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: my-app-backend-migration:latest
        imagePullPolicy: Never
        command: ["node", "/app/src/migrate.js"]
        env:
          - name: DB_HOST
            value: "db-service"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
      restartPolicy: Never
  backoffLimit: 1
