apiVersion: batch/v1
kind: Job
metadata:
  name: migration-backend-deployment
spec:
  template:
    spec:
      containers:
      - name: migration-container
        image: 976193259173.dkr.ecr.eu-central-1.amazonaws.com/my-app_backend-migration:latest
        imagePullPolicy: Always  # Set to Always to pull the latest image from ECR
        envFrom:
        - secretRef:
            name: db-credentials  # Ensure db-credentials secret exists
      restartPolicy: Never
  backoffLimit: 1
