apiVersion: batch/v1
kind: Job
metadata:
  name: migration-backend-deployment
spec:
  template:
    spec:
      containers:
      - name: migration-container
        image: my-app_backend-migration:latest
        imagePullPolicy: Never  # Set to Never to pull the latest image from ECR
        envFrom:
        - secretRef:
            name: db-credentials  # Ensure db-credentials secret exists
      restartPolicy: Never
  backoffLimit: 1
