apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: my-app-backend-migration:latest
        imagePullPolicy: Never
        command: ["node", "/app/src/migrate.js"]
        env:
        - name: MYSQL_DATABASE
          value: myapp_db  # Nome del database
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials  # Secret con la password del root
              key: root_password     # Chiave per la password del root
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials   # Secret con la password dell'utente
              key: username          # Chiave per il nome utente
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials   # Secret con la password dell'utente
              key: password          # Chiave per la password dell'utente
        - name: MYSQL_HOST
          value: "db"  # Nome del servizio del database
        - name: MYSQL_PORT
          value: "3306"  # Porta del database
      restartPolicy: Never
  backoffLimit: 1
