apiVersion: batch/v1
kind: Job
metadata:
  name: migration-backend-deployment
spec:
  template:
    spec:
      containers:
      - name: migration-container
        image: my-app_backend-migration:latest
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 1
