apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: my-app-backend-migration:latest
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 1
