apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database-deployment
  namespace: database-ns
  labels:
    app: mysql-app
spec:
  replicas: 1 # Ensure at least one replica
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql-container
        image: my-app_db # Ensure this image is securely built and scanned
        imagePullPolicy: IfNotPresent # Avoid redundant pulls
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
