apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 976193259173.dkr.ecr.eu-central-1.amazonaws.com/my-app_db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        envFrom:
          - secretRef:
              name: db-credentials
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc