apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: database-ns
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  # MYSQL_HOST: "mysql-service.database-ns" va messo questo nelle globali