apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: database-ns
  labels:
    app: mysql
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: my-app-db  # Assicurati che l'immagine sia presente
        imagePullPolicy: Never  # More flexible pull policy
        ports:
        - containerPort: 3306