apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
spec:
  type: LoadBalancer  # Cambia in ClusterIP o NodePort per esigenze diverse
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: nginx-proxy
