apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: default
spec:
  type: ClusterIP  # Cambiato da LoadBalancer a ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-proxy
