apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
spec:
  type: LoadBalancer  # Tipo ClusterIP, per accesso solo all'interno del cluster
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP  # Non è necessario specificare `nodePort` qui
  selector:
    app: nginx-proxy
