apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }

    http {
        upstream users-app {
            server users-service:3000;
        }

        upstream frontend-expo {
            server frontend-expo-service:8081;
        }

        server {
            listen 8000;

            # Proxy to frontend
            location / {
                proxy_pass http://frontend-expo-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # WebSocket support for Expo
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }

            # Proxy to users service
            location /users/ {
                proxy_pass http://users-service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # Set CORS headers
                add_header Access-Control-Allow-Origin $http_origin always;
                add_header Access-Control-Allow-Credentials true;
                add_header Access-Control-Allow-Methods "GET, POST, DELETE, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";

                # Handle OPTIONS method
                if ($request_method = OPTIONS) {
                    add_header Access-Control-Allow-Origin $http_origin always;
                    add_header Access-Control-Allow-Credentials true;
                    add_header Access-Control-Allow-Methods "GET, POST, DELETE, OPTIONS";
                    add_header Access-Control-Allow-Headers "Content-Type, Authorization";
                    add_header Content-Length 0;
                    add_header Content-Type text/plain;
                    return 204;
                }
            }
            
            # Default 404 for unmatched routes
            error_page 404 /404.html;
            location = /404.html {
                internal;
                return 404;
            }
        }
    }
