apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: frontend-ns
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: my-app-proxy
        imagePullPolicy: Never
        ports:
        - containerPort: 8000