apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories-backend-deployment
  labels:
    app: stories-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stories-app
  template:
    metadata:
      labels:
        app: stories-app
        service: stories-backend-service
    spec:
      containers:
      - name: stories-container
        image: 976193259173.dkr.ecr.eu-central-1.amazonaws.com/my-app_backend-stories:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: db-credentials