apiVersion: v1
kind: Service
metadata:
  name: backend-stories
  labels:
    app: stories-app
spec:
  selector:
    app: stories-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP