apiVersion: v1
kind: Service
metadata:
  name: backend-tts
spec:
  type: ClusterIP # Cambia a NodePort o ClusterIP secondo necessità
  selector:
    app: tts-app
  ports:
    - port: 5000         # Porta esposta per il servizio
      targetPort: 5000   # Porta del container Python
      protocol: TCP
