apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-backend-deployment
  labels:
    app: tts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-app
  template:
    metadata:
      labels:
        app: tts-app
    spec:
      containers:
        - name: tts-container
          image: 976193259173.dkr.ecr.eu-central-1.amazonaws.com/my-app_backend-tts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000