apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-backend-deployment
  labels:
    app: tts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts-app
  template:
    metadata:
      labels:
        app: tts-app
    spec:
      containers:
        - name: tts-container
          image: my-app_backend-tts:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-credentials