apiVersion: v1
kind: Service
metadata:
  name: backend-users
spec:
  selector:
    app: users-app  # Questo deve corrispondere alla label nel deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP