apiVersion: v1
kind: Service
metadata:
  name: users-backend-service
  namespace: backend-ns
  labels:
    app: users-app
spec:
  selector:
    app: users-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
