apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-backend-deployment
  labels:
    app: users-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
        service: users-backend-service
    spec:
      containers:
        - name: users-container
          image: 976193259173.dkr.ecr.eu-central-1.amazonaws.com/my-app_backend-users:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: db-credentials
            - secretRef:
                name: users-key