apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
  namespace: backend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
        service: backend-users  # Aggiunta questa label per maggiore chiarezza
    spec:
      containers:
      - name: users-container
        image: my-app-backend-users
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
